wiki_projects:

('commons','/wiki/','/w/api.php'),
('mediawikiwiki','/wiki/','/w/api.php'),
('metawikimedia','/wiki/','/w/api.php'),
('mw','/wiki/','/w/api.php'),
('wikipedia','/wiki/','/w/api.php'),
('wikiquote','/wiki/','/w/api.php'),
('wikisource','/wiki/','/w/api.php'),
('wikivoyage','/wiki/','/w/api.php'),
('wiktionary','/wiki/','/w/api.php')
